#!/bin/bash



echo "Running pre-commit hook..."



# Check for translated comments and revert them to English

python3 .git/hooks/convert_landmarks.py $(git config user.name)



# Add the reverted files to the commit

git add .
